version: '3.9'

services:
  app:
    build:
      context: .
      target: development
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - app_node_modules:/usr/src/app/node_modules
    command: npm run dev

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: community_board
      MYSQL_USER: community
      MYSQL_PASSWORD: communitypass
    ports:
      - '3307:3306'
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h localhost -uroot -prootpassword']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  app_node_modules:
